name: "PostgreSQL 17"
version: "1.0.0"
slug: "postgresql17"
description: "PostgreSQL 17 database"
url: "https://github.com/mgacic/HassioAddons/PostgreSQL17"
# image: "ghcr.io/mgacic/postgresql17-{arch}"
arch:
  - aarch64
  - amd64
startup: services
init: false
ports:
  5432/tcp: 5432
ports_description:
  5432/tcp: "PostgreSQL Database"
options:
  postgres_db:
    - "homeassistant"
  postgres_user: homeassistant
  postgres_password: password
  postgres_config:
    - "max_connections=50"
    - "shared_buffers=128MB"
schema:
  postgres_db: [str]
  postgres_user: str
  postgres_password: password
  postgres_config: [str]
