name: "n8n"
version: "1.0.0"
slug: "n8n"
description: "n8n Workflow Automation Tool"
url: "https://github.com/mgacic/HassioAddons/n8n"
image: "ghcr.io/mgacic/n8n-{arch}"
arch:
  - aarch64
  - amd64
# startup: application
ingress: true
ingress_port: 5678
ingress_stream: true
init: false
ports:
  5678/tcp: 5678
  8081/tcp: 8081
ports_description:
  5678/tcp: "n8n Web Interface"
  8081/tcp: "n8n webhook and API"

options:
  n8n_basic_auth_active: "true"
  n8n_basic_auth_user: "admin"
  n8n_basic_auth_password: "password"
  n8n_secure_cookie: "false"
  db_type: "sqlite"
  db_postgresdb_host: "core-postgresql16"
  db_postgresdb_port: 5432
  db_postgresdb_database: "n8n"
  db_postgresdb_user: "n8n"
  db_postgresdb_password: ""

schema:
  n8n_basic_auth_active: str
  n8n_basic_auth_user: str
  n8n_basic_auth_password: str
  n8n_secure_cookie: str
  db_type: list(sqlite|postgresdb)
  db_postgresdb_host: str
  db_postgresdb_port: port
  db_postgresdb_database: str
  db_postgresdb_user: str
  db_postgresdb_password: password