name: "n8n"
version: "1.0.0"
slug: "n8n"
description: "n8n Workflow Automation Tool"
url: "https://github.com/mgacic/HassioAddons/n8n"
# image: "ghcr.io/mgacic/n8n-{arch}"
arch:
  - aarch64
  - amd64
startup: services
ingress: true
ingress_port: 5678
init: false
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: "n8n Web Interface"

options:
  n8n_basic_auth_active: "true"
  n8n_basic_auth_user: "admin"
  n8n_basic_auth_password: "password"
  n8n_secure_cookie: "false"

schema:
  n8n_basic_auth_active: str
  n8n_basic_auth_user: str
  n8n_basic_auth_password: str
  n8n_secure_cookie: str