name: "n8n"
version: "1.0.0"
slug: "n8n"
description: "n8n Workflow Automation Tool"
url: "https://github.com/mgacic/HassioAddons/n8n"
arch:
  - aarch64
  - amd64
startup: services
ingress: true
ingress_port: 5678
ingress_stream: true
webui: "http://[HOST]:[PORT:5690]/"
init: false
ports:
  5678/tcp: 5678
  8081/tcp: 8081
ports_description:
  5678/tcp: "n8n Web Interface"
  8081/tcp: "n8n webhook and API"

options:
  n8n_basic_auth_active: "true"
  n8n_basic_auth_user: "admin"
  n8n_basic_auth_password: "password"
  n8n_secure_cookie: "false"

schema:
  n8n_basic_auth_active: str
  n8n_basic_auth_user: str
  n8n_basic_auth_password: str
  n8n_secure_cookie: str